import type { Metadata } from "next";
import { Architects_Daughter } from "next/font/google";
import "./globals.css";

const architectsDaughter = Architects_Daughter({
  weight: "400",
  variable: "--font-architects-daughter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flowly",
  description: "Generated by Flowly",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className="dark">
      <body
        className={`${architectsDaughter.variable} font-architects-daughter antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
